Document: ib-pkey-setup
Title: Debian ib-pkey-setup Manual
Author: <insert document author here>
Abstract: This manual describes what ib-pkey-setup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ib-pkey-setup/ib-pkey-setup.sgml.gz

Format: postscript
Files: /usr/share/doc/ib-pkey-setup/ib-pkey-setup.ps.gz

Format: text
Files: /usr/share/doc/ib-pkey-setup/ib-pkey-setup.text.gz

Format: HTML
Index: /usr/share/doc/ib-pkey-setup/html/index.html
Files: /usr/share/doc/ib-pkey-setup/html/*.html
